### ISSUE TITLE
Serve side rendering makes the server collapse when we receive a socket io message

### ISSUE THREAD

**Issue by vallettea** [anthill/6element#179]
@DavidBruant this one is for you, because we've been struggling on it with @SergeBredin for too long.
pull the develop branch (rm -rf node_modules and npm install) and run 
```
npm run start-dev
```

you can then go on localhost:35000. Here nothing bad.
But when somebody somewhere presses a button on sensor you'll see the whole app crash with this:

```
api_1 | /6element/node_modules/react/node_modules/fbjs/lib/getActiveElement.js:25
api_1 |     return document.body;
api_1 |            ^
api_1 |
api_1 | ReferenceError: document is not defined
api_1 |     at getActiveElement (/6element/node_modules/react/node_modules/fbjs/lib/getActiveElement.js:25:12)
api_1 |     at ReactReconcileTransaction.ReactInputSelection.getSelectionInformation (/6element/node_modules/react/lib/ReactInputSelection.js:38:23)
api_1 |     at ReactReconcileTransaction.Mixin.initializeAll (/6element/node_modules/react/lib/Transaction.js:168:75)
api_1 |     at ReactReconcileTransaction.Mixin.perform (/6element/node_modules/react/lib/Transaction.js:135:12)
api_1 |     at ReactUpdatesFlushTransaction.Mixin.perform (/6element/node_modules/react/lib/Transaction.js:136:20)
api_1 |     at ReactUpdatesFlushTransaction.assign.perform (/6element/node_modules/react/lib/ReactUpdates.js:86:38)
api_1 |     at Object.flushBatchedUpdates (/6element/node_modules/react/lib/ReactUpdates.js:147:19)
api_1 |     at Object.wrapper [as flushBatchedUpdates] (/6element/node_modules/react/lib/ReactPerf.js:66:21)
api_1 |     at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/6element/node_modules/react/lib/Transaction.js:202:25)
api_1 |     at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/6element/node_modules/react/lib/Transaction.js:149:16)
api_1 | [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by vallettea** [comment]
ps: the only way to debug this is to be in the node so you can press the sensor buttons.
I don't know if you'll have time to give it a :gun: but with @SergeBredin we :sob:

**Comment by SergeBredin** [comment]
Socket feature has been removed, as Material UI
